# Generated by Django 4.2.7 on 2023-12-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90)),
                ('content', models.TextField(null=True)),
                ('date', models.DateField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('author', models.CharField(max_length=90)),
            ],
        ),
    ]
