# Generated by Django 4.2.7 on 2023-12-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogMovies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='poster_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
